// Spec for nair-cn-v0.1-doc-001: Qichacha IPO prospectus excerpt.
export default {
  docId: "nair-cn-v0.1-doc-001",
  annotator: "agent-glm-5.2",
  redact: [
    // ===== Issuer company (core party) =====
    { needle: "企查查科技股份有限公司", label: "ORG", severity: "medium", reason: "Named IPO issuer company", all: true },
    { needle: "企查查有限", label: "ORG", severity: "medium", reason: "Named issuer predecessor (limited company form)", all: true },
    { needle: "苏州朗动", label: "ORG", severity: "medium", reason: "Named issuer predecessor entity", all: true },
    // Issuer products (brand identifying the company)
    { needle: "“标找找”", label: "BRAND", severity: "low", reason: "Named company product brand", all: true },
    { needle: "“企查查”会员类产品", label: "BRAND", severity: "low", reason: "Named flagship product brand of the issuer", all: true },
    // ===== Registered contact block (address/postcode/phone/url/email) =====
    { needle: "中国（江苏）自由贸易试验区苏州片区苏州工业园区汇智街 8 号", label: "ADDRESS", severity: "high", reason: "Registered address of the issuer", all: true },
    { needle: "215000", label: "POSTCODE", severity: "high", reason: "Postal code of the issuer", all: true },
    { needle: "400-928-2212", label: "PHONE", severity: "high", reason: "Contact phone number of the issuer", all: true },
    { needle: "www.qcc.com", label: "URL", severity: "medium", reason: "Issuer website URL", all: true },
    { needle: "ir@qcc.com", label: "EMAIL", severity: "high", reason: "Issuer investor-relations email", all: true },
    { needle: "0512-67620509", label: "PHONE", severity: "high", reason: "Information-disclosure officer phone number", all: true },
    // ===== High-tech enterprise certificate number =====
    { needle: "GR202532002384 号", label: "BUSINESS_ID", severity: "high", reason: "High-tech enterprise certificate number of the issuer", all: true },
    // ===== Controller / key person =====
    { needle: "陈德强", label: "PERSON", severity: "high", reason: "Named legal representative / controller of the issuer", all: true },
    { needle: "杨京", label: "PERSON", severity: "high", reason: "Named director / general manager and 5%+ shareholder", all: true },
    { needle: "施阳", label: "PERSON", severity: "high", reason: "Named founder / co-shareholder of the issuer", all: true },
    { needle: "马群", label: "PERSON", severity: "medium", reason: "Named nominee founder (controller's spouse)", all: true },
    { needle: "李素芹", label: "PERSON", severity: "medium", reason: "Named nominee founder (general manager's mother)", all: true },
    { needle: "白燕良", label: "PERSON", severity: "medium", reason: "Named information-disclosure officer / employee shareholder", all: true },
    // Controller & GM ID numbers (national ID) and birth years
    { needle: "3303821985********", label: "NATIONAL_ID", severity: "critical", reason: "National ID number of the controller (masked but identifying)", all: true },
    { needle: "3208021983********", label: "NATIONAL_ID", severity: "critical", reason: "National ID number of the general manager (masked but identifying)", all: true },
    { needle: "1985 年出生", label: "DATE", severity: "high", reason: "Birth year identifying the controller", all: true },
    { needle: "1983 年出生", label: "DATE", severity: "high", reason: "Birth year identifying the general manager", all: true },
    // ===== Shareholders / investors (ORGs and individuals) =====
    { needle: "荷花缘", label: "ORG", severity: "medium", reason: "Named external investor / 5%+ shareholder", all: true },
    { needle: "君安控股", label: "ORG", severity: "medium", reason: "Named external investor shareholder", all: true },
    { needle: "险峰投资", label: "ORG", severity: "medium", reason: "Named external investor / 5%+ shareholder (also private-fund shareholder)", all: true },
    { needle: "苏州知彼", label: "ORG", severity: "medium", reason: "Named employee shareholding platform / 5%+ shareholder", all: true },
    { needle: "苏州知己", label: "ORG", severity: "medium", reason: "Named employee shareholding platform / 5%+ shareholder", all: true },
    { needle: "万得信息", label: "ORG", severity: "medium", reason: "Named original shareholder that transferred shares", all: true },
    { needle: "中信投资", label: "ORG", severity: "medium", reason: "Named external investor that subscribed new shares", all: true },
    { needle: "兴富新兴", label: "ORG", severity: "medium", reason: "Named private-fund shareholder", all: true },
    { needle: "兴富数智", label: "ORG", severity: "medium", reason: "Named private-fund shareholder", all: true },
    { needle: "国方构筑", label: "ORG", severity: "medium", reason: "Named private-fund shareholder", all: true },
    { needle: "元禾鼎业", label: "ORG", severity: "medium", reason: "Named shareholder", all: true },
    // ===== Shareholding-platform and investor full entity names =====
    { needle: "上海荷花缘企业管理中心（有限合伙）", label: "ORG", severity: "medium", reason: "Named full entity name of investor 荷花缘", all: true },
    { needle: "上海万兴信息科技有限公司", label: "ORG", severity: "medium", reason: "Named GP of investor 荷花缘 (and 万得信息 subsidiary)", all: true },
    { needle: "中国（上海）自由贸易试验区浦明路1500号8层Z座", label: "ADDRESS", severity: "high", reason: "Registered premises of investor 荷花缘", all: true },
    { needle: "苏州知彼信息科技中心（有限合伙）", label: "ORG", severity: "medium", reason: "Named full entity name of employee platform 苏州知彼", all: true },
    { needle: "中国（江苏）自由贸易试验区苏州片区苏州工业园区汇智街8号1#研发\n 主要经营场所\n              总部大楼2楼M3室", label: "ADDRESS", severity: "high", reason: "Registered premises of employee platform 苏州知彼", all: true },
    { needle: "苏州知己网络科技中心（有限合伙）", label: "ORG", severity: "medium", reason: "Named full entity name of employee platform 苏州知己", all: true },
    { needle: "中国（江苏）自由贸易试验区苏州片区苏州工业园区汇智街8号1#研发\n主要经营场所\n              总部大楼2楼M2室", label: "ADDRESS", severity: "high", reason: "Registered premises of employee platform 苏州知己", all: true },
    { needle: "杭州险峰投资合伙企业（有限合伙）", label: "ORG", severity: "medium", reason: "Named full entity name of investor 险峰投资", all: true },
    { needle: "西藏险峰长晴创业投资管理有限公司", label: "ORG", severity: "medium", reason: "Named GP of investor 险峰投资", all: true },
    { needle: "浙江省杭州市上城区艮山支三路5号7幢342室", label: "ADDRESS", severity: "high", reason: "Registered premises of investor 险峰投资", all: true },
    { needle: "北京险峰长青投资咨询有限公司", label: "ORG", severity: "medium", reason: "Named fund manager of private-fund shareholder 险峰投资", all: true },
    { needle: "兴富投资管理有限公司", label: "ORG", severity: "medium", reason: "Named fund manager of private-fund shareholders 兴富新兴/兴富数智", all: true },
    { needle: "上海国方私募基金管理有限公司", label: "ORG", severity: "medium", reason: "Named fund manager of private-fund shareholder 国方构筑", all: true },
    // Private-fund filing/registration codes (business identifiers of the funds)
    { needle: "SD6556", label: "BUSINESS_ID", severity: "high", reason: "Private-fund filing code of shareholder 险峰投资", all: true },
    { needle: "SCR848", label: "BUSINESS_ID", severity: "high", reason: "Private-fund filing code of shareholder 兴富新兴", all: true },
    { needle: "SNC111", label: "BUSINESS_ID", severity: "high", reason: "Private-fund filing code of shareholder 兴富数智", all: true },
    { needle: "SGY627", label: "BUSINESS_ID", severity: "high", reason: "Private-fund filing code of shareholder 国方构筑", all: true },
    { needle: "P1003991", label: "BUSINESS_ID", severity: "high", reason: "Fund-manager registration number of 险峰投资's manager", all: true },
    { needle: "P1015277", label: "BUSINESS_ID", severity: "high", reason: "Fund-manager registration number of 兴富's manager", all: true },
    { needle: "P1065092", label: "BUSINESS_ID", severity: "high", reason: "Fund-manager registration number of 国方's manager", all: true },
    // 险峰投资 LP roster (named individuals and entities)
    { needle: "左凌烨", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "刘峻", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "雷量", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "赵铭", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "王辉", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "陈金霞", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "郑伟鹤", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "邵亦文", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "魏炜", label: "PERSON", severity: "medium", reason: "Named limited partner of investor 险峰投资", all: true },
    { needle: "达孜基石创业投资合伙企业（有限合伙）", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    { needle: "浙江普华天勤股权投资管理有限公司", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    { needle: "上海创业接力铂慧投资管理中心", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资 (full suffix line-wrapped in table)" },
    { needle: "绍兴曜灵股权投资合伙企业（有限合伙）", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    { needle: "上海铭武投资咨询事务所", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    { needle: "达孜合业企业管理有限公司", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    { needle: "上海嵩全投资管理有限公司", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    { needle: "西藏御珠企业管理有限公司", label: "ORG", severity: "medium", reason: "Named limited partner (entity) of investor 险峰投资", all: true },
    // ===== Employee platform individual partners =====
    { needle: "尹尚文", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "王金虎", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "童刚", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "朱正亮", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "杜虎", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "陈德志", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "奚威", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "倪传亮", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "邱晶晶", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "任何强", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "王凯", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "丁汉飞", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "李俊", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "刘龙辉", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "陆紫华", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "陈汝龙", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "张全排", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "倪小波", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "何鑫", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "范兆明", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "晏疆", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "王静", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "巫建平", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "刘建伟", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "刘晓", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "李翔", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "曹春雷", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "王铃", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "吴大宝", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "朱伟", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "席鹏", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "俞范磊", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "周建军", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "苏红", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "赵帅", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "李骁", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "李晓伟", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "李卫星", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "黄秉霞", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "陈学松", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "闫东旭", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "李斐", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "曹彬", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "叶秀清", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "陈席", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "孔林涛", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "万春华", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "徐立春", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "张腾飞", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    { needle: "陆梦旦", label: "PERSON", severity: "medium", reason: "Named partner of employee shareholding platform", all: true },
    // ===== Subsidiaries / associates =====
    { needle: "上海知彼", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "北京知彼", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "海南企查查", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "新加坡企查查", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "香港企查查", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "浙江企查查", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "苏州企查查", label: "ORG", severity: "medium", reason: "Named wholly-owned subsidiary of the issuer", all: true },
    { needle: "深圳分公司", label: "ORG", severity: "medium", reason: "Named branch of the issuer", all: true },
    { needle: "苏州墨腾", label: "ORG", severity: "medium", reason: "Named associate company of the issuer", all: true },
    { needle: "虎嗅科技", label: "ORG", severity: "medium", reason: "Named associate company of the issuer", all: true },
    { needle: "北大英华", label: "ORG", severity: "medium", reason: "Named associate company of the issuer", all: true },
    { needle: "无锡行动", label: "ORG", severity: "medium", reason: "Named associate company of the issuer", all: true },
    { needle: "元禾纳芯", label: "ORG", severity: "medium", reason: "Named associate company of the issuer", all: true },
    { needle: "北大资产经营有限公司", label: "ORG", severity: "medium", reason: "Named GP / controller of associate 北大英华", all: true },
    { needle: "苏州工业园区集成电路", label: "ORG", severity: "medium", reason: "Named GP / controller entity of associate 元禾纳芯 (first half, split by table layout)" },
    { needle: "产业投资发展有限公司", label: "ORG", severity: "medium", reason: "Named GP / controller entity of associate 元禾纳芯 (second half, split by table layout)" },
    { needle: "吴涛", label: "PERSON", severity: "medium", reason: "Named controller/GP of associate 苏州墨腾", all: true },
    { needle: "李岷", label: "PERSON", severity: "medium", reason: "Named controller/GP of associate 虎嗅科技", all: true },
    { needle: "孙捷", label: "PERSON", severity: "medium", reason: "Named controller/GP of associate 无锡行动", all: true },
    // ===== Controller's prior employers (identifying the individual's history) =====
    { needle: "新电信息科技（苏州）有限公司", label: "ORG", severity: "low", reason: "Named prior employer of the controller (identifying personal history)", all: true },
    { needle: "江苏欧索软件有限公司", label: "ORG", severity: "low", reason: "Named prior employer of the controller and general manager", all: true },
    { needle: "南京江琛自动化系统\n有限责任公司", label: "ORG", severity: "low", reason: "Named prior employer of the general manager (line-wrapped, identifying personal history)", all: true },
    // ===== Professional intermediaries (named firms) =====
    { needle: "上海东洲资产评估有限公司", label: "ORG", severity: "medium", reason: "Named valuation firm (intermediary)", all: true },
    { needle: "普华永道中天会计师事务所（特殊普通合伙）", label: "ORG", severity: "medium", reason: "Named accounting firm (intermediary)", all: true },
    // Intermediary report numbers (matter-specific references)
    { needle: "东洲评报字\n[2023]第 1183 号", label: "CASE_REF", severity: "medium", reason: "Valuation report number identifying the specific restructuring", all: true },
    { needle: "普华永道中天特审字（2023）第 2616 号", label: "CASE_REF", severity: "medium", reason: "Audit report number identifying the specific restructuring", all: true },
    { needle: "容诚专字[2024]518Z0325 号", label: "CASE_REF", severity: "medium", reason: "Audit review report number identifying the specific restructuring", all: true },
    { needle: "容诚验字[2024]518Z0147 号", label: "CASE_REF", severity: "medium", reason: "Capital verification report number identifying the specific restructuring", all: true },
    // ===== Key identifying dates (establishment & corporate-event dates) =====
    { needle: "2014年3月12日", label: "DATE", severity: "medium", reason: "Establishment date of the issuer", all: true },
    { needle: "2020年9月28日", label: "DATE", severity: "medium", reason: "Establishment date of investor 荷花缘", all: true },
    { needle: "2014年6月4日", label: "DATE", severity: "medium", reason: "Establishment date of investor 险峰投资", all: true },
    { needle: "2015年6月10日", label: "DATE", severity: "medium", reason: "Establishment date of employee platform 苏州知彼", all: true },
    { needle: "2021年11月25日", label: "DATE", severity: "medium", reason: "Establishment date of employee platform 苏州知己", all: true },
    // ===== Key identifying amounts =====
    { needle: "36,225.00万元", label: "AMOUNT", severity: "medium", reason: "Registered capital amount of the issuer", all: true },
  ],
  keep: [
    // Generic law / regulation names (boilerplate, should stay readable).
    { needle: "《征信业\n管理条例》", label: "MUST_KEEP", reason: "Generic regulation name, should remain readable" },
    { needle: "《网络安全法》", label: "MUST_KEEP", reason: "Generic law name, should remain readable" },
    { needle: "《数据安全法》", label: "MUST_KEEP", reason: "Generic law name, should remain readable" },
    { needle: "《私募投资基金监督管理暂行办法》", label: "MUST_KEEP", reason: "Generic regulation name, should remain readable" },
    { needle: "基金登记备案办法》", label: "MUST_KEEP", reason: "Generic regulation name (line-wrapped), should remain readable" },
    { needle: "《关于构建数据基础制度更好发挥数据要素作用的意见》", label: "MUST_KEEP", reason: "Generic policy document name, should remain readable" },
    // Generic regulator / authority names referenced for boilerplate supervision.
    { needle: "中国人民银行", label: "MUST_KEEP", reason: "Generic regulator name (supervision boilerplate)" },
    { needle: "国家数据局", label: "MUST_KEEP", reason: "Generic authority name (policy boilerplate)" },
    // Table headers / structural labels.
    { needle: "注册资本", label: "MUST_KEEP", reason: "Generic table field label, should remain readable" },
    { needle: "认缴出资额（万元）", label: "MUST_KEEP", reason: "Generic table column header" },
  ],
};
