export const AMBIGUOUS_PERSON_TOKENS = new Set([
  "He",
  "May",
  "Will",
  "Mark",
  "Rose",
  "Faith",
  "Hope",
]);

export const SINGLE_PERSON_STOPWORDS = new Set([
  ...AMBIGUOUS_PERSON_TOKENS,
  "Company",
  "Claimant",
  "Respondent",
  "Respondents",
  "Party",
  "Parties",
  "Tribunal",
  "Court",
  "Group",
  "Project",
  "Meeting",
  "Email",
  "Letter",
  "Report",
  "Agreement",
  "Settlement",
  "Arbitration",
  "Statements",
  "Statement",
  "Expert",
  "Enterprise",
  "Phoenix",
  "China",
  "Mainland",
  "Law",
  "Legal",
  "Rules",
  "Ordinance",
  "Companies",
  "Understanding",
  "Summary",
  "Lead",
  "Due",
  "Failure",
  "Parent",
  "Alleged",
  "Loss",
  "Damages",
  "Practice",
  "Government",
  "Subsidies",
  "Director",
  "Managing",
  "Adoption",
  "Evidence",
  "Oral",
  "Examination",
  "Memorandum",
  "Listing",
  "Application",
  "Article",
  "Civil",
  "Code",
  "Society",
  "Private",
  "International",
  "Proceedings",
  "Schedule",
  "Question",
  "Questions",
  "There",
  "This",
  "Request",
  "Requests",
  "Production",
  "Documents",
  "Timetable",
  "Procedural",
  "Financing",
  "Loans",
  "Transactions",
  "Executive",
  "Conclusions",
  "Remuneration",
  "Governance",
  "Costs",
  "Information",
  "Later",
  "Funding",
  "Management",
  "Market",
  "Deputy",
  "Chief",
  "Financial",
  "Officer",
  "January",
  "February",
  "March",
  "April",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
]);

export const KNOWN_ORGS = [
  "HKIAC",
  "HKEx",
  "HKEX",
  "SEHK",
  "SFC",
  "Oaktree",
  "Plainvim",
  "Mountain Road",
  "O'Melveny & Myers",
  "Stock Exchange of Hong Kong",
  "Hong Kong International Arbitration Centre",
  "OMM",
  "Hogan Lovells",
  "Fangda",
  "Deloitte",
  "Colliers",
  "Savills",
  "BNP Paribas",
  "BNP",
  "PwC",
  "PWC",
  "CCBCI",
  "Moody's Analytics",
  "J.P. Morgan",
  "Pacific Alliance Group",
  "Lehman Brothers",
  "Warburg Pincus",
  "De Heng",
  "DeHeng",
  "Wharton",
  "Wingtech",
  "Cocoa",
  "Cocoa Partners",
  "Tanner De Witt",
  "Clifford Chance",
  "Forum",
  "MoFo",
  "Kempinski Hotel",
  "Four Seasons",
  "BAM",
  "Brookfield",
  "PIBL",
  "PILB",
  "P Group",
  "HSBC",
  "UOB",
  "LUSO",
  "EY",
  "ESR",
  "Ping An",
  "So, Lung & Associates",
  "Llinks Law Offices",
  "China Society of Private International Law",
];

export const MATTER_TERMS = [
  "Commission Agreement",
  "Arbitration Agreement",
  "Procedural Order No.1",
  "Procedural Order No",
  "Procedural Order",
  "PO No.1",
  "Amendment to Schedule A",
  "Amendment No.2",
  "Amendment No. 2",
  "Amendment Agreements",
  "Shareholders' Agreement",
  "Shareholders Agreement",
  "Subscription Agreement",
  "SHA",
  "SSA",
  "SSHA",
  "PSA",
  "MOU",
  "Draft MOU",
  "Record of Negotiation Terms",
  "11 October Meeting Summary",
  "October Meeting Summary",
  "Government Subsidies",
  "Future Government Subsidies",
  "Future Subsidies",
  "government incentive grants",
  "Government Subsidies Understanding",
  "Nei Bao Wai Dai",
  "Neibaowaidai",
  "neibaowaidai",
  "neibaowaidaI",
  "Chang An Project",
  "Chang An Assets",
  "Chang An assets",
  "Chang An transaction",
  "Chang An settlement",
  "Chang An",
  "Chang'an transactions",
  "Chang'an transaction",
  "Chang'an settlement",
  "Chang'an",
  "Changan transaction",
  "Changan settlement",
  "Changan",
  "Dongkeng Industrial Parks",
  "Dongkeng Assets",
  "Dongkeng assets",
  "Dongkeng Park",
  "Dongkeng subsidiary",
  "Dongkeng",
  "Dong Keng",
  "KETD Project",
  "KETD project",
  "KETD",
  "ICETD Project",
  "ICETD",
  "Huatai financing",
  "Huatai",
  "Haimen Park",
  "Haimen project",
  "Haimen",
  "Nano-metal Advanced Materials",
  "Dongfeng excluded park",
  "Dongfeng",
  "Taicang Park",
  "Changshu Park",
  "Jiaxing Industrial Park",
  "Jiaxing",
  "Zhaoqing",
  "Xiangcheng",
  "Dongguan",
  "Nanhai",
  "Pingmao loan contract",
  "Pingmao",
  "Longping property-rights transaction",
  "Longping",
  "Out of Group Assets",
  "out-of-group assets",
  "Peninsula Settlement Agreement",
  "Peninsula settlement",
  "Peninsula document",
  "Peninsula consensus",
  "Peninsula Hotel",
  "Peninsula meeting",
  "Peninsula",
  "Established Practice",
];

export const LOCATION_TERMS = [
  "Shenzhen, China",
  "Hong Kong SAR",
  "Hong Kong",
  "Shanghai",
  "Shenzhen",
  "Foshan",
  "Taicang",
  "Changshu",
  "Kunshan",
  "Qingdao",
];

export const PROPER_NOUN_STOP_TERMS = new Set([
  "Table of Contents",
  "Witnesses",
  "Claimant",
  "Respondents",
  "Background",
  "The Parties",
  "Oral Examination",
  "Working Group Meeting",
  "Share Option Scheme",
  "Reserved Matters",
  "Listing Rules",
  "Companies Ordinance",
  "Mainland China",
  "Hong Kong",
  "Hong Kong SAR",
  "New York",
  "Sole Arbitrator",
  "Procedural Timetable",
  "Document Request Schedule",
  "Deputy Chief Financial Officer",
  "Chief Operating Officer",
]);

