export const AMBIGUOUS_PERSON_TOKENS = new Set([
  "He",
  "May",
  "Will",
  "Mark",
  "Rose",
  "Faith",
  "Hope",
]);

export const SINGLE_PERSON_STOPWORDS = new Set([
  ...AMBIGUOUS_PERSON_TOKENS,
  "Company",
  "Claimant",
  "Respondent",
  "Respondents",
  "Party",
  "Parties",
  "Tribunal",
  "Court",
  "Group",
  "Project",
  "Meeting",
  "Email",
  "Letter",
  "Report",
  "Hearing",
  "Bundle",
  "Agreement",
  "Settlement",
  "Arbitration",
  "Statements",
  "Statement",
  "Expert",
  "Enterprise",
  "Phoenix",
  "China",
  "Mainland",
  "Law",
  "Legal",
  "Rules",
  "Ordinance",
  "Companies",
  "Understanding",
  "Summary",
  "Lead",
  "Due",
  "Failure",
  "Parent",
  "Alleged",
  "Loss",
  "Damages",
  "Practice",
  "Government",
  "Subsidies",
  "Director",
  "Managing",
  "Adoption",
  "Evidence",
  "Oral",
  "Examination",
  "Memorandum",
  "Listing",
  "Application",
  "Article",
  "Civil",
  "Code",
  "Society",
  "Private",
  "International",
  "Proceedings",
  "Schedule",
  "Question",
  "Questions",
  "There",
  "This",
  "Request",
  "Requests",
  "Production",
  "Documents",
  "Timetable",
  "Procedural",
  "Financing",
  "Loans",
  "Transactions",
  "Executive",
  "Conclusions",
  "Remuneration",
  "Governance",
  "Costs",
  "Information",
  "Later",
  "Funding",
  "Management",
  "Market",
  "Deputy",
  "Chief",
  "Financial",
  "Officer",
  // Procurement role labels. These are never plausible standalone person-name
  // components but can appear in title-case lists/labels ("Purchaser,",
  // "Supplier Name:", "The Vendor shall ..."). Adding them keeps these role
  // words readable instead of redacting them as people.
  "Purchaser",
  "Supplier",
  "Vendor",
  "Bidder",
  "Contractor",
  "Subcontractor",
  "Procurement",
  "Buyer",
  // Boilerplate tokens that are never plausible standalone person-name
  // components but that the contextual/parenthetical/standalone detectors
  // sometimes bundle into a "name": "Not Applicable", "Central European
  //  Time", "European Union", "Time Zone". Adding them here keeps these
  // phrases readable instead of redacting them as people.
  "Not",
  "Applicable",
  "Central",
  "European",
  "Time",
  "Zone",
  "January",
  "February",
  "March",
  "April",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
]);

// Multiword phrases that END in one of these tokens are organizations, not
// people (e.g. "Cisco Systems", "American Airlines", "Travel Solutions",
// "Pegasus Systems", "SunTrust Capital Markets"). Used to stop contextual /
// list person detectors from turning company names into PERSON candidates,
// which also prevents bogus given-name aliases ("Cisco", "Sabre", ...).
//
// NOTE: true legal suffixes (Inc, Corp, LLC, Ltd, Company, Corporation,
// Limited, ...) are deliberately EXCLUDED. Those are handled by the
// ORG_SUFFIX_NAME_TOKENS path in addPersonAliases so that a company caught
// by a role pattern (e.g. "Respondent Northwind Inc.") can still yield a
// short-form alias for its standalone mentions. The tokens here are the
// softer, suffix-less org tails.
//
// Curated to exclude real surnames (Cooper, Davis, Walker, Mason, Young,
// Reed, Hale, ...) so genuine people are never suppressed by this rule.
export const ORG_NAME_TAIL_TOKENS = new Set([
  "Systems",
  "System",
  "Solutions",
  "Services",
  "Service",
  "Networks",
  "Network",
  "Airlines",
  "Airline",
  "Airways",
  "Railways",
  "Railway",
  "Logistics",
  "Freight",
  "Shipping",
  "Motors",
  "Technologies",
  "Electronics",
  "Industries",
  "Industrial",
  "Materials",
  "Chemicals",
  "Sciences",
  "Biotech",
  "Pharma",
  "Pharmaceuticals",
  "Pharmaceutical",
  "Medical",
  "Hospitals",
  "Hospital",
  "Pipeline",
  "Pipelines",
  "Energy",
  "Electric",
  "Investments",
  "Investment",
  "Partners",
  "Affiliates",
  "Markets",
  "Bank",
  "Bancorp",
  "Express",
  "Vacations",
  "Stores",
  "Brands",
  "Foods",
  "Beverages",
  "Restaurants",
  "Retail",
  "Retailers",
  "Association",
  "Council",
  "Councils",
  "Society",
  "Institute",
  "Foundation",
  "Federation",
  "University",
  "Universities",
  "Press",
  "Media",
  "Holdings",
  "Group",
  "Groups",
  // Government / regulator agency tail words. A capitalized phrase ending in
  // one of these is an agency name (e.g. "Drug Administration", "Trade
  // Commission", "Protection Authority"), never a person surname. They appear
  // in regulatory enforcement and compliance notices and must stay readable
  // instead of being redacted as people.
  "Administration",
  "Commission",
  "Department",
  "Agency",
  "Bureau",
  "Authority",
  "Directorate",
  "Inspectorate",
]);

// Recognizable global organizations commonly seen in English business/legal documents.
// These complement the suffix-based organization detection with a small, auditable allowlist.
export const GENERAL_ORGS = [
  "Goldman Sachs",
  "Morgan Stanley",
  "KPMG",
  "McKinsey",
  "Allen & Overy",
  "Linklaters",
  "Freshfields",
  "DLA Piper",
  "Baker McKenzie",
  "BlackRock",
  "Blackstone",
  "Citigroup",
  "Barclays",
  "Deutsche Bank",
  "Credit Suisse",
  "UBS",
];

// Corpus-specific organizations carried over from the original arbitration prototype.
// Consider moving these into an opt-in config when generalizing further.
export const KNOWN_ORGS = [
  "HKIAC",
  "HKEx",
  "HKEX",
  "SEHK",
  "SFC",
  "Oaktree",
  "Plainvim",
  "Mountain Road",
  "O'Melveny & Myers",
  "Hong Kong International Arbitration Centre",
  "OMM",
  "Hogan Lovells",
  "Fangda",
  "Deloitte",
  "Colliers",
  "Savills",
  "BNP Paribas",
  "BNP",
  "PwC",
  "PWC",
  "CCBCI",
  "Moody's Analytics",
  "J.P. Morgan",
  "Pacific Alliance Group",
  "Lehman Brothers",
  "Warburg Pincus",
  "De Heng",
  "DeHeng",
  "Wharton",
  "Wingtech",
  "Cocoa",
  "Cocoa Partners",
  "Tanner De Witt",
  "Clifford Chance",
  "MoFo",
  "Kempinski Hotel",
  "Four Seasons",
  "BAM",
  "Brookfield",
  "PIBL",
  "PILB",
  "P Group",
  "HSBC",
  "UOB",
  "LUSO",
  "EY",
  "ESR",
  "Ping An",
  "So, Lung & Associates",
  "Llinks Law Offices",
  "China Society of Private International Law",
];

// Corpus-specific matter glossary from the original arbitration prototype.
// These terms are case-specific; keep them clearly labeled and prefer structural
// detection for new document types.
export const MATTER_TERMS = [
  "Commission Agreement",
  "Arbitration Agreement",
  "Procedural Order No.1",
  "Procedural Order No",
  "Procedural Order",
  "PO No.1",
  "Amendment to Schedule A",
  "Amendment No.2",
  "Amendment No. 2",
  "Amendment Agreements",
  "Shareholders' Agreement",
  "Shareholders Agreement",
  "Subscription Agreement",
  "SHA",
  "SSA",
  "SSHA",
  "PSA",
  "MOU",
  "Draft MOU",
  "Record of Negotiation Terms",
  "11 October Meeting Summary",
  "October Meeting Summary",
  "Government Subsidies",
  "Future Government Subsidies",
  "Future Subsidies",
  "government incentive grants",
  "Government Subsidies Understanding",
  "Nei Bao Wai Dai",
  "Neibaowaidai",
  "neibaowaidai",
  "neibaowaidaI",
  "Chang An Project",
  "Chang An Assets",
  "Chang An assets",
  "Chang An transaction",
  "Chang An settlement",
  "Chang An",
  "Chang'an transactions",
  "Chang'an transaction",
  "Chang'an settlement",
  "Chang'an",
  "Changan transaction",
  "Changan settlement",
  "Changan",
  "Dongkeng Industrial Parks",
  "Dongkeng Assets",
  "Dongkeng assets",
  "Dongkeng Park",
  "Dongkeng subsidiary",
  "Dongkeng",
  "Dong Keng",
  "KETD Project",
  "KETD project",
  "KETD",
  "ICETD Project",
  "ICETD",
  "Huatai financing",
  "Huatai",
  "Haimen Park",
  "Haimen project",
  "Haimen",
  "Nano-metal Advanced Materials",
  "Dongfeng excluded park",
  "Dongfeng",
  "Taicang Park",
  "Changshu Park",
  "Jiaxing Industrial Park",
  "Jiaxing",
  "Zhaoqing",
  "Xiangcheng",
  "Dongguan",
  "Nanhai",
  "Pingmao loan contract",
  "Pingmao",
  "Longping property-rights transaction",
  "Longping",
  "Out of Group Assets",
  "out-of-group assets",
  "Peninsula Settlement Agreement",
  "Peninsula settlement",
  "Peninsula document",
  "Peninsula consensus",
  "Peninsula Hotel",
  "Peninsula meeting",
  "Peninsula",
  "Established Practice",
];

// Broadly useful world locations. Safe to extend for broader English coverage.
export const GENERAL_LOCATIONS = [
  "London",
  "New York",
  "Singapore",
  "Tokyo",
  "Beijing",
  "San Francisco",
  "Los Angeles",
  "Chicago",
  "Boston",
  "Frankfurt",
  "Paris",
  "Zurich",
  "Sydney",
  "Melbourne",
  "Toronto",
  "Vancouver",
  "Dubai",
  "Seoul",
];

// Locations carried over from the original arbitration prototype.
// These are corpus-specific; move to opt-in config when generalizing further.
export const CORPUS_LOCATIONS = [
  "Shenzhen, China",
  "Hong Kong SAR",
  "Hong Kong",
  "Shanghai",
  "Shenzhen",
  "Foshan",
  "Taicang",
  "Changshu",
  "Kunshan",
  "Qingdao",
];

export const LOCATION_TERMS = [...GENERAL_LOCATIONS, ...CORPUS_LOCATIONS];

export const PROPER_NOUN_STOP_TERMS = new Set([
  "Table of Contents",
  "Witnesses",
  "Claimant",
  "Respondents",
  "Background",
  "The Parties",
  "Oral Examination",
  "Working Group Meeting",
  "Share Option Scheme",
  "Reserved Matters",
  "Listing Rules",
  "Companies Ordinance",
  "Mainland China",
  "Hong Kong",
  "Hong Kong SAR",
  "New York",
  "Sole Arbitrator",
  "Procedural Timetable",
  "Document Request Schedule",
  "Deputy Chief Financial Officer",
  "Chief Operating Officer",
  "Hearing Bundle",
  // Stock-exchange / listed-issuer regulatory boilerplate. These phrases are
  // standard across HKEX, SGX, ASX, and LSE/AIM filings and identify neither
  // the issuer nor an individual; redacting them at heavy only harms
  // readability of mandatory disclosure language.
  "Stock Exchange",
  "The Stock Exchange",
  "Hong Kong Exchanges and Clearing",
  "London Stock Exchange",
  "Singapore Exchange",
  "Annual General Meeting",
  "Extraordinary General Meeting",
  "Company Secretary",
  "Proxy Form",
  "Results Announcement",
  "Registration Statement",
  "Listing Rule",
  "Listing Manual",
  "Main Board Rule",
  "GEM Rule",
  "AIM Rules",
  "AIM rules for companies",
  "Annual Report",
  "Directors’ Report",
  "Auditor’s Report",
  "Remuneration Report",
  "Financial Report",
  "Sustainability Report",
  "Explanatory Statement",
  "Notice of Meeting",
  "Notice of Annual General Meeting",
  "Ordinary Resolution",
  "Ordinary Resolution No",
  "Ordinary Shares",
  "Performance Rights",
  "For personal use only",
  "Non-Executive Director",
  "Independent Director",
  "Executive Director",
  "Group Chief Executive Officer",
  "Chief Executive Officer",
  // Procurement document boilerplate. These phrases identify neither a
  // vendor nor an individual; redacting them at heavy only harms
  // readability of standard solicitation/PO/contract language.
  "Scope of Work",
  "Statement of Work",
  "Terms and Conditions",
  "Contract Award Notice",
  "Accounts Payable",
  "Request for Proposal",
  "Request for Quotation",
  "Invitation for Bid",
  "Procurement Officer",
  "Procurement Manager",
  "Purchase Order",
  // Finance operations / accounts-payable boilerplate. These standard invoice,
  // remittance, and AP labels identify neither a vendor nor an individual;
  // redacting them at heavy only harms readability of finance documents.
  "Remittance Advice",
  "Payment Terms",
  "Net 30",
  "Net 60",
  "Net 90",
  "Subtotal",
  "Total Due",
  "Balance Due",
  "Payment Due",
  "Bill To",
  "Ship To",
  "Remit To",
]);

// Common title-case words that should not, by themselves, turn a capitalized
// phrase into a redacted proper noun in heavy mode.
export const COMMON_TITLE_WORDS = new Set([
  "The",
  "This",
  "That",
  "These",
  "Those",
  "Such",
  "Any",
  "All",
  "Some",
  "Other",
  "Said",
  "Above",
  "Below",
  "Pursuant",
  "Thereto",
  "Hereof",
  "Hereunder",
  "Herein",
  "Therein",
  "Whereas",
  "Shall",
  "Will",
  "Would",
  "May",
  "Must",
  "Should",
  "Could",
  "Following",
  "Aforesaid",
  "Hereby",
  "Thereby",
]);

// Capitalized tokens that are ubiquitous defined-term role labels, financial
// concepts, document sections, or legal/property terms in commercial contracts.
// When any of these appears as a token inside a candidate "person name", the
// candidate is almost always boilerplate (e.g. "Administrative Agent",
// "Common Stock", "Base Rent", "Intellectual Property"), not a person.
// Tokens are deliberately chosen to never be plausible person-name components.
// Keep this auditable and resist adding words that are also common surnames.
export const CONTRACT_DEFINED_TERM_TOKENS = new Set([
  // Contracting parties / roles
  "Tenant",
  "Tenants",
  "Landlord",
  "Landlords",
  "Lessor",
  "Lessee",
  "Seller",
  "Sellers",
  "Buyer",
  "Buyers",
  "Purchaser",
  "Purchasers",
  "Borrower",
  "Borrowers",
  "Lender",
  "Lenders",
  "Guarantor",
  "Guarantors",
  "Agent",
  "Agents",
  "Administrative",
  "Escrow",
  "Trustee",
  "Trustees",
  "Licensor",
  "Licensee",
  "Sponsor",
  "Operator",
  "Operators",
  "Franchisor",
  "Franchisee",
  "Assignor",
  "Assignee",
  "Issuer",
  "Holder",
  "Holders",
  "Underwriter",
  "Underwriters",
  "Consignor",
  "Consignee",
  "Indemnitee",
  "Indemnitor",
  "Indemnified",
  "Indemnification",
  "Indemnity",
  // Financial / monetary concepts
  "Rent",
  "Rents",
  "Base",
  "Basic",
  "Additional",
  "Monthly",
  "Annual",
  "Annualized",
  "Quarterly",
  "Weekly",
  "Daily",
  "Taxes",
  "Tax",
  "Indebtedness",
  "Expenses",
  "Expense",
  "Expenditures",
  "Operating",
  "Fee",
  "Fees",
  "Charge",
  "Charges",
  "Premium",
  "Premiums",
  "Price",
  "Prices",
  "Pricing",
  "Compensation",
  "Remuneration",
  "Income",
  "Revenue",
  "Revenues",
  "Payment",
  "Payments",
  "Money",
  "Funds",
  "Fund",
  "Capital",
  "Capitalized",
  "Stock",
  "Stocks",
  "Shares",
  "Share",
  "Securities",
  "Registrable",
  // Securities-class defined terms used in prospectuses and opinion letters
  // ("Debt Securities", "Preferred Stock", "Depositary Shares", "Common
  //  Stock", "Preferred Securities"). These qualifiers are never plausible
  //  standalone person-name components; adding them stops the list/person
  //  detectors from redacting defined terms as people.
  "Debt",
  "Preferred",
  "Depositary",
  "Depository",
  "Warrants",
  "Units",
  "Equity",
  "Equities",
  "Dividend",
  "Dividends",
  "Principal",
  "Deposit",
  "Deposits",
  "Liability",
  "Liabilities",
  "Collateral",
  "Margin",
  "Mortgage",
  "Mortgages",
  "Pledge",
  "Interest",
  "Interests",
  "Asset",
  "Assets",
  "Payables",
  "Receivables",
  "Consideration",
  "Royalty",
  "Royalties",
  "Bonus",
  "Bonuses",
  "Pension",
  "Benefit",
  "Benefits",
  // HR / employment defined terms ("Severance Payment", "Stay Bonus",
  // "Occupational Safety", "Sign-On Bonus"). Not plausible name components.
  "Severance",
  "Occupational",
  "Sign-On",
  "Bonus",
  // Property / IP / assets
  "Property",
  "Properties",
  "Premises",
  "Lease",
  "Leases",
  "Estate",
  "Real",
  "Common",
  "Area",
  "Maintenance",
  "Improvements",
  "Demised",
  "Materials",
  "Material",
  "Hazardous",
  "Environmental",
  "Permits",
  "Permit",
  "Authorizations",
  "Authorization",
  "Approvals",
  "Approval",
  "Intellectual",
  "Patent",
  "Patents",
  "Trademark",
  "Trademarks",
  "Copyright",
  "Copyrights",
  "Technology",
  "Software",
  "Data",
  "Information",
  // Agreement / document structure
  "Agreement",
  "Agreements",
  "Contract",
  "Contracts",
  "Notice",
  "Notices",
  "Amendment",
  "Amendments",
  "Waiver",
  "Waivers",
  "Consent",
  "Consents",
  "Default",
  "Events",
  "Event",
  "Termination",
  "Renewal",
  "Expiration",
  "Effective",
  "Execution",
  "Version",
  "Copy",
  "Confidential",
  "Confidentiality",
  "Disclosure",
  "Representations",
  "Warranties",
  "Warranty",
  "Representation",
  "Provisions",
  "Conditions",
  "Definitions",
  "Accounting",
  "Covenants",
  "Covenant",
  "Obligations",
  "Obligation",
  "Records",
  "Schedule",
  "Schedules",
  "Exhibit",
  "Exhibits",
  "Appendix",
  "Section",
  "Sections",
  "Article",
  "Articles",
  "Clause",
  "Certificate",
  "Certificates",
  "Drawings",
  "Drawing",
  "Plans",
  "Plan",
  "Form",
  "Forms",
  "Order",
  "Orders",
  "Report",
  "Reports",
  "Quantity",
  "Minimums",
  "Specification",
  "Specifications",
  "Confirmation",
  "Description",
  "Term",
  "Terms",
  "Date",
  "Page",
  "Signature",
  "Signatures",
  // Corporate governance / roles
  "Board",
  "Directors",
  "Director",
  "Officers",
  "Officer",
  "Committee",
  "Executive",
  "President",
  "Vice",
  "Secretary",
  "Treasurer",
  "Manager",
  "Managers",
  "Managing",
  "Employee",
  "Employees",
  "Employment",
  "Employer",
  "Personnel",
  "Chairman",
  "Chief",
  "General",
  // Standing board-committee qualifiers ("Audit Committee",
  // "Nominating Committee", "Governance Committee", "Ethics Committee").
  // These are governance/structural concepts, never plausible surname
  // components; adding them keeps the standard board committees readable
  // instead of being redacted as organizations or people.
  "Audit",
  "Nominating",
  "Governance",
  "Ethics",
  // Government / regulatory / legal
  "Act",
  "Acts",
  "Code",
  "Laws",
  "Ordinance",
  "Statute",
  "Statutes",
  "Regulations",
  "Rules",
  "Government",
  "State",
  "Federal",
  "National",
  "Authority",
  "Authorities",
  "License",
  "Licenses",
  "Registration",
  "Registry",
  "Reform",
  "Recovery",
  "Protection",
  "Conservation",
  "Accountability",
  "Portability",
  "Insurance",
  "Health",
  "Safety",
  "Compliance",
  "Labor",
  "Consumer",
  "Commerce",
  "Administration",
  "Agency",
  "Services",
  "Service",
  "Welfare",
  // Descriptive qualifiers common in defined terms
  "Completion",
  "Pre-Completion",
  "Excluded",
  "Non-Excluded",
  "Estimated",
  "Final",
  "Initial",
  "Applicable",
  "Selected",
  "Subject",
  "Owned",
  "Licensed",
  "Related",
  "Permitted",
  "Restricted",
  "Available",
  "Required",
  "Specified",
  "Designated",
  "Net",
  "Gross",
  "Personal",
  "Liability",
  "Force",
  "Majeure",
  "Quiet",
  "Enjoyment",
  "Holding",
  // Products / scope / process terms
  "Product",
  "Products",
  "Development",
  "Activities",
  "Activity",
  "Commercialization",
  "Commercialize",
  "Supplied",
  "Components",
  "Component",
  "Access",
  "Limited",
  "Procedures",
  "Procedure",
  "Borrowing",
  "Commitment",
  "Commitments",
  "Contents",
  "Social",
  "Security",
  "Male",
  "Female",
  "Public",
  "Mail",
  "States",
  "Sale",
  "Sales",
  "Notary",
  "Official",
  "Health",
  // Litigation / regulatory / agency vocabulary
  // These are ubiquitous in pleadings, complaints, consent orders, and agency
  // filings. None are plausible standalone person-name components. Adding them
  // here prevents boilerplate phrases such as "Commission Act", "Exchange
  // Act", "Relief Defendant", "Prayer for Relief", and "Trade Commission"
  // from being treated as person names.
  "Commission",
  "Commissions",
  "Defendant",
  "Defendants",
  "Plaintiff",
  "Plaintiffs",
  "Petitioner",
  "Petitioners",
  "Respondent",
  "Respondents",
  "Relator",
  "Relators",
  "Intervenor",
  "Intervenors",
  "Amicus",
  "Movant",
  "Movants",
  "Appellant",
  "Appellants",
  "Appellee",
  "Decedent",
  "Debtor",
  "Debtors",
  "Creditor",
  "Creditors",
  "Complaint",
  "Judgment",
  "Decree",
  "Relief",
  "Prayer",
  "Jurisdiction",
  "Venue",
  "Claim",
  "Claims",
  "Count",
  "Counts",
  "Allegation",
  "Allegations",
  "Injunction",
  "Sanction",
  "Sanctions",
  "Restitution",
  "Disgorgement",
  "Forfeiture",
  "Penalty",
  "Penalties",
  "Verdict",
  "Ruling",
  "Indictment",
  "Subpoena",
  "Summons",
  "Discovery",
  "Motion",
  "Motions",
  "Trial",
  "Appeal",
  "Appeals",
  "Counsel",
  "Antitrust",
  "Enforcement",
  "Division",
  "Bureau",
  "Department",
  "Securities",
  "Exchange",
  "Trade",
  "Firm",
  "Firms",
  "Corporation",
  "Corporations",
  "Hosting",
  "Platform",
  "Infrastructure",
  "Jury",
  "District",
  "Entity",
  "Entities",
  "Factual",
  "Relevant",
  "Deceptive",
  "Review",
  // Additional common qualifiers that appear in headings and product names
  // in litigation/regulatory filings. Not plausible person-name components.
  "United",
  "Shared",
  "Customer",
  "Managed",
  "Business",
  "Practices",
  "Practice",
  // Correspondence / prospectus / operational-document vocabulary. These are
  // section headings, role labels, financial line items, and table column
  // names ubiquitous in SEC correspondence, counsel letters, offering circulars,
  // and 10-K responses. None are plausible standalone person-name components.
  // Curated to avoid real surnames (Brown, White, Green, Young, Long, Short,
  // Strong, Grant, King, Page, etc. are deliberately excluded).
  // Section / document headings
  "Risk",
  "Factors",
  "Strategy",
  "Strategic",
  "Offering",
  "Circular",
  "Preliminary",
  "Sheet", // "Balance Sheet"
  "Cash", // "Cash Equivalents" (≥2 rule keeps "Patrick Cash" safe)
  "Equivalents",
  "Equivalent",
  "Proceeds",
  "Use", // "Use of Proceeds"
  "Background",
  "Industry",
  "Overview",
  "Introduction",
  "Summary",
  "Description",
  "Contents", // "Table of Contents"
  "Table",
  "Investment", // "Investment Objectives"
  "Investments",
  "Professional", // "Professional Background"
  "Transaction", // "Transaction Processing"
  "Transactions",
  "Selling", // "Selling Shareholders"
  "Shareholder",
  "Shareholders",
  "Account", // "Account Forms"
  "Accounts",
  "Forms",
  "Form",
  "Scope", // "Scope and Transferability"
  "Custody", // "Safe Custody"
  "Arrangements", // "Client Money Arrangements"
  "Marital", // "Marital Status"
  "Status",
  "Method",
  "Approved",
  "Applicable",
  "Internal",
  "Holder",
  "Holders",
  "Named",
  "Print",
  "Certain", // "Certain Relationships"
  "Relationships",
  "Relationship",
  "Competitive",
  "Proprietary",
  "Rights",
  "Worldwide",
  "Global",
  "Reach",
  "Presence",
  "Leading",
  "Superior",
  "Opportunity",
  "Solution",
  "Solutions",
  "Marketplace",
  "Awareness",
  "Enhance",
  "Expand",
  "Internationally",
  "Supplier",
  "Suppliers",
  "Vendor",
  "Vendors",
  "Strengths",
  "Capacity",
  "Capacities",
  "Limitations",
  "Pronouncements",
  "Recent",
  "Going",
  "Concern",
  "Liquidation",
  "Refund",
  "Disbursement",
  "Billings",
  "Booking",
  "Usage",
  "Penetration",
  "Aggregate",
  "Mailing",
  "Delivery",
  "Instructions",
  "Instruction",
  "Telephone",
  "Calculation",
  "Certification",
  "Signed",
  "Signatures",
  "Processing",
  "Objectives",
  "Advice",
  "Extraordinary",
  "Events",
  "Headings",
  "Descriptive",
  "Transferability",
  "Several",
  "Indication",
  "Non-Investment",
  // Role / title labels common in signature blocks and contact lines
  "Staff",
  "Attorney",
  "Attorneys",
  "Counsel",
  "Senior",
  "Junior",
  "Vice",
  "President",
  "Manager",
  "Managers",
  "Operations",
  "Controller",
  "Comptroller",
  "Treasurer",
  "Assistant",
  "Deputy",
  "Coordinator",
  "Director",
  "Directors",
  "Representative",
  "Representatives",
  "Specialist",
  "Specialists",
  "Analyst",
  "Analysts",
  "Consultant",
  "Consultants",
  "Advisor",
  "Advisors",
  "Adviser",
  "Advisers",
  "Department",
  "Division",
  "Office",
  "Unit",
  "Resources", // "Human Resources"
  "Personnel",
  "Employee",
  "Employees",
  // Org-name tail tokens (multiword phrases ending in these are companies,
  // not people). Extends the suffix-based org detector to common tails that
  // lack a punctuation form. None are plausible surname-only components.
  "Systems",
  "System",
  "Network",
  "Networks",
  "Airlines",
  "Airline",
  "Railway",
  "Railways",
  "Energy",
  "Electric",
  "Gas",
  "Oil",
  "Pipeline",
  "Pipelines",
  "Hospital",
  "Hospitals",
  "Medical",
  "Pharma",
  "Pharmaceutical",
  "Sciences",
  "Biotech",
  "Logistics",
  "Freight",
  "Shipping",
  "Motors",
  "Technologies",
  "Software",
  "Hardware",
  "Electronics",
  "Industries",
  "Industrial",
  "Materials",
  "Chemicals",
  "Steel",
  "Mining",
  "Foods",
  "Beverages",
  "Restaurants",
  "Retail",
  "Stores",
  "Brands",
]);

// Generalized address vocabulary used to drive structural address detection
// without hard-coding a single jurisdiction.
export const STREET_SUFFIXES = [
  "Road",
  "Street",
  "Avenue",
  "Lane",
  "Boulevard",
  "Drive",
  "Court",
  "Place",
  "Crescent",
  "Way",
  "Terrace",
  "Parkway",
  "Trail",
  "Walk",
  "Mews",
  "Close",
  "Quay",
  "Grove",
  "Heights",
  "Circle",
  "Square",
  "Vale",
  "View",
  "Expressway",
  "Highway",
  "Gardens",
  "Fields",
  "Yard",
  "Row",
  "Rd",
  "St",
  "Ave",
  "Ln",
  "Blvd",
  "Dr",
  "Ct",
  "Pl",
  "Cres",
  "Ter",
  "Hwy",
  "Expy",
];

export const UNIT_INDICATORS = [
  "Unit",
  "Room",
  "Rm",
  "Suite",
  "Ste",
  "Flat",
  "Apartment",
  "Apt",
  "Floor",
  "Fl",
  "Level",
  "Shop",
  "Lot",
  "Studio",
  "Penthouse",
  "Basement",
  "Mezzanine",
];

export const BUILDING_KEYWORDS = [
  "Building",
  "Bldg",
  "Tower",
  "Towers",
  "Centre",
  "Center",
  "House",
  "Plaza",
  "Point",
  "Estate",
  "Mall",
  "Complex",
  "Block",
  "Wing",
  "Annex",
];
